[zellij-harpoon]
src.github_tag = "Nacho114/harpoon"
fetch.url = "https://github.com/Nacho114/harpoon/releases/download/$ver/harpoon.wasm"

[zellij-vertical-tabs]
src.github_tag = "cfal/zellij-vertical-tabs"
fetch.url = "https://github.com/cfal/zellij-vertical-tabs/releases/download/$ver/zellij-vertical-tabs.wasm"
