# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  herdr-remote = {
    pname = "herdr-remote";
    version = "5c51dbc5fc053ea1a851089584e2886a1fde148f";
    src = fetchFromGitHub {
      owner = "dcolinmorgan";
      repo = "herdr-remote";
      rev = "5c51dbc5fc053ea1a851089584e2886a1fde148f";
      fetchSubmodules = false;
      sha256 = "sha256-fwsPjQLJZrm5Xm5ttC3RNmoYF81ANt9Q660rrHmyCs0=";
    };
    date = "2026-07-09";
  };
  herdr-splits = {
    pname = "herdr-splits";
    version = "19b9782c8d1941449bdb3376379adaa2444166a9";
    src = fetchFromGitHub {
      owner = "lmilojevicc";
      repo = "herdr-splits.nvim";
      rev = "19b9782c8d1941449bdb3376379adaa2444166a9";
      fetchSubmodules = false;
      sha256 = "sha256-Xl21R3ZcyWt7Q8/jzbnl8hhMXDPxLkizXUKj5YnlGyc=";
    };
    date = "2026-07-15";
  };
  tmux-fzf = {
    pname = "tmux-fzf";
    version = "05af76daa2487575b93a4f604693b00969f19c2f";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "tmux-fzf";
      rev = "05af76daa2487575b93a4f604693b00969f19c2f";
      fetchSubmodules = false;
      sha256 = "sha256-ay7z0MkeDCpxdwNTKFrkxi/hUE7a5K7P7oFhfn94aLA=";
    };
    date = "2025-09-24";
  };
  zellij-harpoon = {
    pname = "zellij-harpoon";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/Nacho114/harpoon/releases/download/v0.3.0/harpoon.wasm";
      sha256 = "sha256-f4z1enHx27vRFTN6MWOHgNfhjpuHbe8cgclwGIyqMvI=";
    };
  };
  zellij-vertical-tabs = {
    pname = "zellij-vertical-tabs";
    version = "v0.1.0";
    src = fetchurl {
      url = "https://github.com/cfal/zellij-vertical-tabs/releases/download/v0.1.0/zellij-vertical-tabs.wasm";
      sha256 = "sha256-UxCRtWqzvAAIvRTeGfcZheOrhYURDuAh747kE1ViAqI=";
    };
  };
}
