# This file was generated by nvfetcher, please do not modify it manually.
{fetchurl}: {
  zellij-harpoon = {
    pname = "zellij-harpoon";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/Nacho114/harpoon/releases/download/v0.3.0/harpoon.wasm";
      sha256 = "sha256-f4z1enHx27vRFTN6MWOHgNfhjpuHbe8cgclwGIyqMvI=";
    };
  };
  zellij-vertical-tabs = {
    pname = "zellij-vertical-tabs";
    version = "v0.1.0";
    src = fetchurl {
      url = "https://github.com/cfal/zellij-vertical-tabs/releases/download/v0.1.0/zellij-vertical-tabs.wasm";
      sha256 = "sha256-UxCRtWqzvAAIvRTeGfcZheOrhYURDuAh747kE1ViAqI=";
    };
  };
}
