# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  herdr-remote = {
    pname = "herdr-remote";
    version = "bb70162eb6d3ab6413974b14cdd7f3763f14a38c";
    src = fetchFromGitHub {
      owner = "dcolinmorgan";
      repo = "herdr-remote";
      rev = "bb70162eb6d3ab6413974b14cdd7f3763f14a38c";
      fetchSubmodules = false;
      sha256 = "sha256-bbsZfOIFjKWFOiVjettZcUykVVuGRc/9Y5rSqKPorsY=";
    };
    date = "2026-10-08";
  };
  herdr-splits = {
    pname = "herdr-splits";
    version = "94f30cf4e9ac76ddf185a3acd0977be728fa4106";
    src = fetchFromGitHub {
      owner = "lmilojevicc";
      repo = "herdr-splits.nvim";
      rev = "94f30cf4e9ac76ddf185a3acd0977be728fa4106";
      fetchSubmodules = false;
      sha256 = "sha256-7rHAPSjd2n16FGOcqI/1KNHl1yCmMOVVwiJl/eEU9n8=";
    };
    date = "2026-08-17";
  };
  tmux-fzf = {
    pname = "tmux-fzf";
    version = "e5f427e9dcf180ca92e2f8af47ba07f644fd4585";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "tmux-fzf";
      rev = "e5f427e9dcf180ca92e2f8af47ba07f644fd4585";
      fetchSubmodules = false;
      sha256 = "sha256-VikPQHZMZroL77k+j1MSq9XwzOu35mYXYU9x2pqHDks=";
    };
    date = "2026-08-10";
  };
  zellij-harpoon = {
    pname = "zellij-harpoon";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/Nacho114/harpoon/releases/download/v0.3.0/harpoon.wasm";
      sha256 = "sha256-f4z1enHx27vRFTN6MWOHgNfhjpuHbe8cgclwGIyqMvI=";
    };
  };
  zellij-vertical-tabs = {
    pname = "zellij-vertical-tabs";
    version = "v0.1.0";
    src = fetchurl {
      url = "https://github.com/cfal/zellij-vertical-tabs/releases/download/v0.1.0/zellij-vertical-tabs.wasm";
      sha256 = "sha256-UxCRtWqzvAAIvRTeGfcZheOrhYURDuAh747kE1ViAqI=";
    };
  };
}
